### ISSUE TITLE
Criação do Minesweeper

### ISSUE THREAD

**Issue by Mayara-tech** [projeto-de-algoritmos/Grafos1_Minesweeper#1]
## DESCRIÇÃO
O jogo Minesweeper é um jogo de tabuleiro que consiste em um grid de células, onde algumas células contêm minas ocultas. O objetivo do jogo é revelar todas as células que não contêm minas sem detonar uma mina. Cada célula revelada pode ter um número, que indica quantas minas estão presentes nas células adjacentes.

A implementação usa grafos para representar o tabuleiro do jogo, onde cada célula é um nó do grafo e as arestas são as conexões entre as células adjacentes. Essa representação é útil para a implementação do algoritmo Flood Fill, que é usado para revelar todas as células que não contêm minas e que são adjacentes a uma célula inicial.

## OBJETIVO
desenvolver um jogo de Campo Minado funcional em JavaScript, garantindo que o jogo atenda aos requisitos definidos e ofereça uma experiência de jogo satisfatória para os usuários.

## TAREFAS
- [x] Definição dos requisitos: definir os requisitos do jogo, incluindo o número de células, a quantidade de minas e os critérios para determinar o fim do jogo.
- [x]  Criação de um README completo e bem estruturado.
- [x] Projeto da interface do usuário: projetar uma interface amigável e fácil de usar, incluindo recursos como botões de reinício, marcadores de minas e pontuações.
- [x] Implementação do jogo: implementar o jogo de acordo com os requisitos definidos, incluindo a lógica do jogo, os eventos de clique, as funções para detecção de minas e a geração aleatória do campo minado.
- [x] Testes e depuração: realizar testes rigorosos para garantir que o jogo esteja funcionando de forma adequada, depurando eventuais problemas encontrados.
- [x] Otimização do desempenho: otimizar o código do jogo para garantir que ele seja rápido e responsivo, mesmo em dispositivos com baixo poder de processamento.

## TEMPO ESTIMADO
Esta tarefa pode ser concluída em até duas semanas.

**Comment by MillenaQueiroz** [comment]
Material de Apoio:
- [Flood Fill](https://noic.com.br/materiais-informatica/curso/graphs-02/)
- [Como iniciar um projeto Node JS](https://dicasdejavascript.com.br/como-criar-um-projeto-nodejs-com-npm/)
- [Implementação de Graph em js](https://acervolima.com/implementacao-de-graph-em-javascript/)
